# Site settings
title: QViz SDK
email: srinivasan.annamalai@qviz.io
description: >- # this means to ignore newlines until "baseurl:"
  QViz SDK (Quality Visualizations Software Development Kit) is for
  working with the QViz Product APIs in any application.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sdk.qviz.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: PeriscopeTechno
github_username:  periscope-tech
show_downloads: true

# GitHub Pages Settings
lsi: false
safe: true
source: "/docs"
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Build settings
markdown: kramdown
theme: jekyll-theme-leap-day
plugins:
  - jekyll-feed
github: [metadata]
